add non-zero exit code in terminal prompt & include timestamp in history

diff --git a/env b/env
--- a/env
+++ b/env
@@ -58,7 +58,7 @@ export CATALINA_HOME=/mnt/e/Programs/apache-tomcat-9.0.63/
 
 export HISTFILESIZE=10000        # increase history file size (default is 500)
 export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
-
+export HISTTIMEFORMAT="%F %T "          ## Adds time to history
 
 
 # Software Related
@@ -80,3 +80,20 @@ export DOTSWB="$DOTSW/bin"
 export LOGDIR="/mnt/c/Users/sandr/logs"
 export WTMP="/mnt/c/Users/sandr/AppData/Local/Temp"
 
+# initial PS1
+# PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
+
+# ubuntu show return code in terminal prompt -> https://stackoverflow.com/questions/16715103/bash-prompt-with-the-last-exit-code
+PROMPT_COMMAND=__prompt_command
+
+__prompt_command() {
+    local exitCode="$?"                # This needs to be first
+    local exitCodeInPrompt=""
+
+    local RCol='\[\e[0m\]'
+    local Red='\[\e[0;31m\]'
+
+    [ $exitCode != 0 ] && exitCodeInPrompt=" ${Red}${exitCode}${RCol}"
+
+    PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]${exitCodeInPrompt}\$ "
+}
