[yt_playlist_archive()] change how chat id is set + log chat id in yt_playlist_archive.py + add alias for 2ndary chat

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1526,11 +1526,14 @@ function yt_playlist_archive() {
     local chatId
     local mode
 
-    chatId="${1:-$YT_PLAYLIST_ARCHIVE_TELEGRAM_BOT_CHAT_ID}"
+    chatId="${CHAT_ID:-$YT_PLAYLIST_ARCHIVE_TELEGRAM_BOT_CHAT_ID}"
     mode="${MODE:-both}"
 
-    usage="usage: ${FUNCNAME[0]} <start position> <end position> [<telegram chat id>]"
-    (( $# >=2 && $# <= 3 )) || { echo "ERROR: ${usage}"; return 1; }
+    echo "chatId=${chatId}"
+    echo "mode=${mode}"
+
+    usage="usage: [CHAT_ID=...] [MODE=...] ${FUNCNAME[0]} <start position> <end position>"
+    (( $# == 2 )) || { echo "ERROR: ${usage}"; return 1; }
 
     takeoutRepo="/mnt/e/git/sp-backups-z/google-takeout-youtube"
     oldpwd="$OLDPWD"
